---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: mcr.microsoft.com/dotnet/sdk
    tag: 8.0.101-alpine3.18-amd64
inputs:
- name: source
params:
  PROJECT:
run:
  path: /bin/sh
  args:
  - -c
  - |
    cd "source/${PROJECT}"

    # For some reason, dotnet build fails with
    # /usr/share/dotnet/sdk/5.0.103/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB6004: The specified task executable location "/rootfs/usr/share/dotnet/dotnet" is invalid. [/tmp/build/6da1d659/source/PdfSharpCore/PdfSharpCore.csproj]
    # ...
    # Microsoft.Build.BackEnd.NodeFailedToLaunchException: No such file or directory
    #
    # I can't find why "/rootfs" is prepended on concourse but works fine in the same docker image running in other environments
    # Hack is to create this directory structure for now and symlink dotnet binary there
    mkdir -p /rootfs/usr/share/dotnet/
    ln -s /usr/share/dotnet/dotnet /rootfs/usr/share/dotnet/dotnet

    dotnet build /p:GeneratePackageOnBuild=False -c Release "${PROJECT}.csproj"
